name: Delinea Secret via GitHub Actions
run-name: ${{ github.actor }} is requesting secret from Delinea 🚀
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Retrieve secrets from Delinea
        env:
          DPSS_RETRIEVE: |
            [
              {"secretId":"75","secretKey":"access-key","outputVariable":"AWS-ACCESS-KEY"}
            ]
        run: |
          docker run --rm \
            -e DPSS_SERVER_URL="${{ secrets.DPSS_SERVER_URL }}" \
            -e DPSS_CLIENT_ID="${{ secrets.DPSS_CLIENT_ID }}" \
            -e DPSS_CLIENT_SECRET="${{ secrets.DPSS_CLIENT_SECRET }}" \
            -e DELINEA_RETRIEVE="$DPSS_RETRIEVE" \
            -e GITHUB_ENV=/github_env \
            -v "$GITHUB_ENV:/github_env" \
            delineaxpm/dpss-github-action:latest

      - name: Mask retrieved secrets in logs
        run: |
          echo "::add-mask::$AWS-ACCESS-KEY"

      - name: Use the retrieved secrets
        run: |
          echo "AWS Access Key: $AWS-ACCESS-KEY"
